# Generated by Django 5.2.5 on 2025-08-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(help_text="설정 키", max_length=100, unique=True),
                ),
                ("value", models.TextField(help_text="설정 값")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("integer", "정수"),
                            ("string", "문자열"),
                            ("boolean", "불린"),
                            ("float", "실수"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="설정 설명", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "설정",
                "verbose_name_plural": "설정들",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system", "시스템"),
                            ("channel_check", "채널 체크"),
                            ("download", "다운로드"),
                            ("notification", "알림"),
                            ("cleanup", "정리"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(help_text="로그 메시지")),
                (
                    "data",
                    models.JSONField(blank=True, help_text="추가 데이터 (JSON)", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "시스템 로그",
                "verbose_name_plural": "시스템 로그들",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["level"], name="core_system_level_bf5286_idx"),
                    models.Index(
                        fields=["category"], name="core_system_categor_1fe2d6_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="core_system_created_19c977_idx"
                    ),
                ],
            },
        ),
    ]
