# Generated by Django 5.2.5 on 2025-08-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0002_channel_check_interval_minutes_channel_last_live_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestream",
            name="last_retry_at",
            field=models.DateTimeField(blank=True, help_text="마지막 재시도 시간", null=True),
        ),
        migrations.AddField(
            model_name="livestream",
            name="retry_count",
            field=models.IntegerField(default=0, help_text="다운로드 재시도 횟수"),
        ),
        migrations.AddField(
            model_name="livestream",
            name="retry_enabled",
            field=models.BooleanField(default=True, help_text="재시도 활성화 여부"),
        ),
    ]
