# Generated by Django 5.2.5 on 2025-08-10 14:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        help_text="YouTube 채널 ID (예: UC...)", max_length=50, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="채널 이름", max_length=200)),
                (
                    "url",
                    models.URLField(
                        help_text="채널 URL",
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="모니터링 활성화 여부"),
                ),
                (
                    "last_checked",
                    models.DateTimeField(blank=True, help_text="마지막 확인 시간", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "YouTube 채널",
                "verbose_name_plural": "YouTube 채널들",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="LiveStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_id",
                    models.CharField(
                        help_text="YouTube 비디오 ID", max_length=50, unique=True
                    ),
                ),
                ("title", models.CharField(help_text="라이브 스트림 제목", max_length=500)),
                ("url", models.URLField(help_text="라이브 스트림 URL")),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, help_text="썸네일 URL", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("live", "라이브 중"),
                            ("ended", "종료됨"),
                            ("downloading", "다운로드 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="live",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="라이브 시작 시간"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, help_text="라이브 종료 시간", null=True),
                ),
                (
                    "notification_sent",
                    models.BooleanField(default=False, help_text="알림 발송 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_streams",
                        to="channels.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "라이브 스트림",
                "verbose_name_plural": "라이브 스트림들",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["video_id"], name="channels_li_video_i_a5cc00_idx"
                    ),
                    models.Index(
                        fields=["channel", "status"],
                        name="channels_li_channel_dc4e86_idx",
                    ),
                    models.Index(
                        fields=["-started_at"], name="channels_li_started_1fbafd_idx"
                    ),
                ],
            },
        ),
    ]
