# Generated by Django 5.1.2 on 2025-08-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="check_interval_minutes",
            field=models.IntegerField(
                default=5, help_text="체크 주기 (분). 채널 활동에 따라 자동 조정됨"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="last_live_at",
            field=models.DateTimeField(blank=True, help_text="마지막 라이브 시간", null=True),
        ),
    ]
