# Generated by Django 5.1.2 on 2025-08-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("channels", "0002_channel_check_interval_minutes_channel_last_live_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[("best", "고화질"), ("worst", "저화질")],
                        default="best",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("downloading", "다운로드 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                            ("cancelled", "취소됨"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="파일 크기 (바이트)"),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, help_text="다운로드 진행률 (0-100)"),
                ),
                (
                    "download_speed",
                    models.CharField(
                        blank=True, help_text="다운로드 속도", max_length=50, null=True
                    ),
                ),
                (
                    "eta",
                    models.CharField(
                        blank=True, help_text="예상 완료 시간", max_length=50, null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "task_id",
                    models.CharField(
                        blank=True, help_text="Celery 태스크 ID", max_length=255, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0, help_text="재시도 횟수")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "live_stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="channels.livestream",
                    ),
                ),
            ],
            options={
                "verbose_name": "다운로드",
                "verbose_name_plural": "다운로드들",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "quality"],
                        name="downloads_d_status_b256d6_idx",
                    ),
                    models.Index(
                        fields=["live_stream", "quality"],
                        name="downloads_d_live_st_ab9ec1_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="downloads_d_created_b33fcd_idx"
                    ),
                ],
            },
        ),
    ]
