# Generated by Django 5.1.2 on 2025-08-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='delete_after',
            field=models.DateTimeField(blank=True, help_text='자동 삭제 예정 시간', null=True),
        ),
    ]
