# Generated by Django 5.2.5 on 2025-08-11 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0002_download_delete_after"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="download",
            name="audio_codec",
            field=models.CharField(
                blank=True, help_text="오디오 코덱 (예: aac, opus)", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="download",
            name="backup_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "대기중"),
                    ("uploading", "업로드중"),
                    ("completed", "완료"),
                    ("failed", "실패"),
                ],
                help_text="백업 상태",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="download",
            name="drive_url",
            field=models.URLField(
                blank=True, help_text="Google Drive 공유 링크", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="download",
            name="fps",
            field=models.IntegerField(blank=True, help_text="프레임레이트", null=True),
        ),
        migrations.AddField(
            model_name="download",
            name="resolution",
            field=models.CharField(
                blank=True,
                help_text="해상도 (예: 1920x1080, 1080p)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="download",
            name="video_codec",
            field=models.CharField(
                blank=True, help_text="비디오 코덱 (예: h264, vp9)", max_length=50, null=True
            ),
        ),
        migrations.CreateModel(
            name="ManualDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(help_text="YouTube 영상 URL", max_length=500)),
                (
                    "video_id",
                    models.CharField(
                        blank=True, help_text="YouTube 비디오 ID", max_length=50, null=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "channel_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "duration",
                    models.IntegerField(blank=True, help_text="영상 길이 (초)", null=True),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "download_type",
                    models.CharField(
                        choices=[("server", "서버 저장"), ("direct", "CDN 다이렉트")],
                        default="server",
                        max_length=10,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        default="best", help_text="다운로드 품질 설정", max_length=10
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="파일 크기 (바이트)"),
                ),
                (
                    "direct_url",
                    models.URLField(
                        blank=True, help_text="CDN 다이렉트 URL", max_length=1000, null=True
                    ),
                ),
                (
                    "direct_url_expires",
                    models.DateTimeField(
                        blank=True, help_text="다이렉트 URL 만료 시간", null=True
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        help_text="해상도 (예: 1920x1080)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("video_codec", models.CharField(blank=True, max_length=50, null=True)),
                ("audio_codec", models.CharField(blank=True, max_length=50, null=True)),
                ("fps", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("extracting", "정보 추출 중"),
                            ("downloading", "다운로드 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, help_text="다운로드 진행률 (0-100)"),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("drive_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "backup_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "대기중"),
                            ("uploading", "업로드중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "수동 다운로드",
                "verbose_name_plural": "수동 다운로드들",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="downloads_m_status_a5c2f3_idx"
                    ),
                    models.Index(
                        fields=["video_id"], name="downloads_m_video_i_8c081d_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="downloads_m_created_4a2d99_idx"
                    ),
                ],
            },
        ),
    ]
